// ملف about-server.tsx
import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Appsssssss",
  description: "Generated by create next app",
};

export default function AboutServer() {
  return <div className="font-mono">About Page (Server)</div>;
}