import React, { useEffect } from "react";

import getQueryClient from "@/lib/get-query-client";
import { HydrationBoundary, dehydrate } from "@tanstack/react-query";
import { Users } from "./Users";
import { request } from "../../../lib/axios";
import type { Metadata } from "next";
import Head from "next/head";
import AboutServer from "./about-server";
import { getUser } from "@/lib/functions";

export const metadata: Metadata = {
  title: "About App",
  description: "Generated by create next app",
};


async function ProjectsPage() {
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery({
    queryKey: ["user"],
    queryFn: () => getUser("todos"),
  });

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <AboutServer />
      <Users />
    </HydrationBoundary>
  );
}
export default ProjectsPage;
